defmodule Wenche.SkattemeldingPersonlig do
  @moduledoc """
  Validation and submission of the **personlig** skattemelding for an ENK
  (enkeltpersonforetak) to Skatteetaten / Altinn 3.

  Companion to `Wenche.Skattemelding` (which handles the upersonlig / AS case).
  The two share the næringsspesifikasjon and request-envelope generators in
  `Wenche.SkattemeldingXml`; this module supplies the personlig-specific pieces:

    * the outer document is the personlig `skattemelding` (v13), generated by
      `Wenche.SkattemeldingPersonligXml`;
    * the næringsspesifikasjon is generated with `skattepliktig_type: :personlig`
      (ENK virksomhetstype, owner-allocated næringsresultat);
    * the request envelope uses `skattemelding_dokumenttype: "skattemeldingPersonlig"`;
    * the draft `partsreferanse` / dokumentreferanse are resolved via
      `Wenche.SkdSkattemeldingClient.hent_utkast_referanse_personlig/3`.

  Unlike the AS flow there is **no** 22 % corporate-tax `beregn`: an ENK owner's
  personal tax (trinnskatt, trygdeavgift) is assessed by Skatteetaten. The
  `skattemessig næringsresultat` is the figure kontio supplies; the assessed
  result comes back from `/valider`'s etter-beregning.

  ## Authentication

  Same split as `Wenche.Skattemelding`: validation uses a Maskinporten +
  systemuser token (`SkdSkattemeldingClient`); submission requires an
  ID-porten-derived Altinn token (`AltinnClient`).
  """

  alias Wenche.{AltinnClient, SkattemeldingPersonligXml, SkattemeldingXml, SkdSkattemeldingClient}
  alias Wenche.Models.Aarsregnskap

  @dokumenttype "skattemeldingPersonlig"

  @doc """
  Computes the figures kontio displays for an ENK næringsspesifikasjon.

  Returns the skattemessig næringsresultat (regnskapsmessig resultat adjusted by
  any `:permanent_forskjeller`) plus a balance overview. The assessed personal
  tax is not computed here — it comes from Skatteetaten's etter-beregning.

  ## Options

  - `:permanent_forskjeller` — optional list (see
    `Wenche.SkattemeldingXml.generer_permanent_forskjell_block/1`).
  """
  @spec beregn(Aarsregnskap.t(), keyword()) :: %{
          selskap: %{navn: String.t(), org_nummer: String.t()},
          regnskapsaar: integer(),
          skattemessig_naeringsresultat: integer()
        }
  def beregn(%Aarsregnskap{} = regnskap, opts \\ []) do
    pf = Keyword.get(opts, :permanent_forskjeller, [])
    s = regnskap.selskap

    %{
      selskap: %{navn: s.navn, org_nummer: s.org_nummer},
      regnskapsaar: regnskap.regnskapsaar,
      skattemessig_naeringsresultat:
        Wenche.Skattemelding.derive_skattepliktig_brutto(regnskap, pf)
    }
  end

  @doc """
  Builds the three XML documents for a personlig skattemelding submission:
  `{skattemelding_personlig, naeringsspesifikasjon, request_envelope}`.

  Accepts the resolved draft reference (`%{partsnummer:, skattemelding_id:,
  naering_id:}` — `partsnummer` carries the partsreferanse) so callers can build
  the XML without re-fetching. See `valider/3` / `send_inn/3` for the
  fetch-and-build flow.

  ## Options

  - `:partsidentifikator` — the tax subject's identifier (the ENK owner's
    fnr/d-nummer) used for the envelope `<tin>`. Defaults to the org number.
  - `:kontaktperson`, `:permanent_forskjeller` — forwarded to the
    næringsspesifikasjon generator.
  - `:fremfoerbar_negativ_personinntekt` — positive integer kroner of negative
    beregnet personinntekt carried forward from earlier years (skatteloven
    § 12-13). Forwarded to the personlig skattemelding generator; when absent or
    non-positive the personlig shell stays minimal. See
    `Wenche.SkattemeldingPersonligXml`.
  """
  @spec bygg_xmls(Aarsregnskap.t(), map(), keyword()) ::
          {String.t(), String.t(), String.t()}
  def bygg_xmls(%Aarsregnskap{} = regnskap, ref, opts) do
    aar = regnskap.regnskapsaar
    org = regnskap.selskap.org_nummer

    naering_opts =
      [skattepliktig_type: :personlig, partsnummer: ref.partsnummer]
      |> maybe_forward_opt(opts, :permanent_forskjeller)
      |> maybe_forward_opt(opts, :kontaktperson)

    skattemelding_opts =
      [partsreferanse: ref.partsnummer]
      |> maybe_forward_opt(opts, :fremfoerbar_negativ_personinntekt)
      |> maybe_forward_opt(opts, :naeringstype)

    skattemelding_xml =
      SkattemeldingPersonligXml.generer_skattemelding_personlig_xml(
        regnskap,
        skattemelding_opts
      )

    naering_xml = SkattemeldingXml.generer_naeringsspesifikasjon_xml(regnskap, naering_opts)

    request_xml =
      SkattemeldingXml.generer_request_xml(
        skattemelding_xml,
        naering_xml,
        request_envelope_opts(opts, aar, org, ref)
      )

    {skattemelding_xml, naering_xml, request_xml}
  end

  @doc """
  Validates the personlig skattemelding against Skatteetaten's `/valider` API.

  Resolves the draft partsreferanse + dokumentreferanse via `skd_client`
  (unless a `:partsreferanse` is supplied in `opts`), builds the envelope, and
  posts it.

  Pass `:partsidentifikator` (the ENK owner's fnr/d-nummer) so the draft lookup
  and `/valider` are keyed by the tax subject rather than the org number.

  Returns `{:ok, validation_body}` or `{:error, reason}`.
  """
  @spec valider(Aarsregnskap.t(), SkdSkattemeldingClient.t(), keyword()) ::
          {:ok, binary()} | {:error, term()}
  def valider(%Aarsregnskap{} = regnskap, %SkdSkattemeldingClient{} = skd_client, opts \\ []) do
    aar = regnskap.regnskapsaar
    org = regnskap.selskap.org_nummer
    # The draft lookup and /valider are keyed by the tax subject. For a personlig
    # return that is the owner's fnr/d-nummer (:partsidentifikator), not the org.
    subject = Keyword.get(opts, :partsidentifikator, org)

    case resolve_utkast_referanse(opts, skd_client, aar, subject) do
      {:ok, ref} ->
        {_sm, _ne, request_xml} = bygg_xmls(regnskap, ref, opts)
        SkdSkattemeldingClient.valider(skd_client, aar, subject, request_xml)

      {:error, reason} ->
        {:error, {:utkast_referanse_failed, reason}}
    end
  end

  @doc """
  Submits the personlig skattemelding to Skatteetaten via Altinn 3.

  Mirrors `Wenche.Skattemelding.send_inn/4` (same `skattemelding` app flow);
  pass a `:skd_client` so the draft partsreferanse + dokumentreferanse are
  fetched (without it SKD rejects the submission).

  Returns `{:ok, inbox_url}` or `{:error, reason}`.
  """
  @spec send_inn(Aarsregnskap.t(), AltinnClient.t(), keyword()) ::
          {:ok, term()} | {:error, term()}
  def send_inn(%Aarsregnskap{} = regnskap, %AltinnClient{} = client, opts \\ []) do
    aar = regnskap.regnskapsaar
    org = regnskap.selskap.org_nummer
    subject = Keyword.get(opts, :partsidentifikator, org)
    skd_client = Keyword.get(opts, :skd_client)

    case resolve_utkast_referanse(opts, skd_client, aar, subject) do
      {:ok, ref} ->
        {_sm, _ne, request_xml} = bygg_xmls(regnskap, ref, opts)
        # NB: the Altinn instance is still created on the enterprise (org) as the
        # avgiver/reportee — only the SKD draft + envelope tin use the subject.
        do_send_inn(client, org, aar, request_xml)

      {:error, reason} ->
        {:error, {:utkast_referanse_failed, reason}}
    end
  end

  defp do_send_inn(client, org, aar, request_xml) do
    with {:ok, instans} <- AltinnClient.opprett_instans(client, "skattemelding", org),
         {:ok, _} <-
           AltinnClient.oppdater_data_element(
             client,
             "skattemelding",
             instans,
             "Skattemeldingsapp_v2",
             Jason.encode!(%{inntektsaar: aar}),
             "application/json"
           ),
         {:ok, _} <-
           AltinnClient.last_opp_skattemelding_konvolutt(client, instans, request_xml),
         {:ok, _} <- AltinnClient.neste_prosesssteg(client, "skattemelding", instans) do
      AltinnClient.fullfoor_instans(client, "skattemelding", instans)
    end
  end

  @doc """
  Parses Skatteetaten's `/valider` response, extracting SKD-computed values from
  the embedded `skattemeldingPersonligEtterBeregning` document.

  Best-effort: returns a map with the fields that are present, or `%{}` when the
  etter-beregning document is absent. Keys:

    * `:partsreferanse`, `:inntektsaar`
    * `:personinntekt` — the assessed beregnet personinntekt
      (`samordnetPersoninntekt/personinntekt/beloep/beloepSomHeltall`)
    * `:aarets_fremfoerbare_negativ_personinntekt` — the negative beregnet
      personinntekt SKD computed as carry-forward *to next year* (skatteloven
      § 12-13). Persist this and submit it next year as
      `:fremfoerbar_negativ_personinntekt` (see `bygg_xmls/3`). Absent/`nil`
      when this year's personinntekt is non-negative.
  """
  @spec parse_etter_beregning(binary()) :: map()
  def parse_etter_beregning(body) when is_binary(body) do
    case extract_etter_beregning_xml(body) do
      nil ->
        %{}

      inner ->
        %{
          partsreferanse: extract_int(inner, "partsreferanse"),
          inntektsaar: extract_int(inner, "inntektsaar"),
          personinntekt: extract_beloep_som_heltall(inner, "personinntekt"),
          aarets_fremfoerbare_negativ_personinntekt:
            extract_beloep_som_heltall(inner, "aaretsFremfoerbareNegativPersoninntekt")
        }
    end
  end

  def parse_etter_beregning(_), do: %{}

  # ── helpers ─────────────────────────────────────────────────────────

  defp resolve_utkast_referanse(opts, skd_client, aar, subject) do
    case Keyword.get(opts, :partsreferanse) do
      partsreferanse when is_integer(partsreferanse) ->
        {:ok,
         %{
           partsnummer: partsreferanse,
           skattemelding_id: Keyword.get(opts, :dokumentidentifikator),
           naering_id: nil
         }}

      _ ->
        if is_nil(skd_client) do
          {:ok, %{partsnummer: subject, skattemelding_id: nil, naering_id: nil}}
        else
          SkdSkattemeldingClient.hent_utkast_referanse_personlig(skd_client, aar, subject)
        end
    end
  end

  defp request_envelope_opts(opts, aar, org, ref) do
    # For a personlig (ENK) return the tax subject is the owner, not the
    # enterprise — callers pass the owner's fnr/d-nummer as :partsidentifikator.
    # Falls back to the org number for backward compatibility.
    tin = Keyword.get(opts, :partsidentifikator, org)

    base =
      [inntektsaar: aar, tin: tin, skattemelding_dokumenttype: @dokumenttype]
      |> maybe_put(:opprettet_av, Keyword.get(opts, :opprettet_av))
      |> maybe_put(:innsendingstype, Keyword.get(opts, :innsendingstype))
      |> maybe_put(:innsendingsformaal, Keyword.get(opts, :innsendingsformaal))

    sm_id = ref.skattemelding_id || Keyword.get(opts, :dokumentidentifikator)
    ne_id = ref.naering_id

    refs =
      []
      |> append_ref(@dokumenttype, sm_id)
      |> append_ref("naeringsspesifikasjon", ne_id)

    if refs == [], do: base, else: Keyword.put(base, :dokumentreferanse, refs)
  end

  defp extract_etter_beregning_xml(body) do
    pattern =
      ~r{<(?:\w+:)?dokument>\s*<(?:\w+:)?type>\s*skattemeldingPersonligEtterBeregning\s*</(?:\w+:)?type>\s*<(?:\w+:)?encoding>[^<]*</(?:\w+:)?encoding>\s*<(?:\w+:)?content>\s*([^<]+?)\s*</(?:\w+:)?content>}s

    case Regex.run(pattern, body) do
      [_, b64] ->
        case Base.decode64(String.replace(b64, ~r/\s+/, "")) do
          {:ok, xml} -> xml
          :error -> nil
        end

      _ ->
        nil
    end
  end

  defp extract_int(xml, tag) do
    case Regex.run(~r{<(?:\w+:)?#{tag}>\s*([-0-9]+)\s*</(?:\w+:)?#{tag}>}, xml) do
      [_, num] -> String.to_integer(num)
      _ -> nil
    end
  end

  # Extracts the integer from a `BeloepSomHeltallMedSkattemessigeEgenskaper`-shaped
  # element: `<tag><beloep><beloepSomHeltall>N</beloepSomHeltall></beloep></tag>`.
  # Returns the first match's integer, or nil when the element is absent.
  defp extract_beloep_som_heltall(xml, tag) do
    pattern =
      ~r{<(?:\w+:)?#{tag}>\s*<(?:\w+:)?beloep>\s*<(?:\w+:)?beloepSomHeltall>\s*([-0-9]+)\s*</(?:\w+:)?beloepSomHeltall>}s

    case Regex.run(pattern, xml) do
      [_, num] -> String.to_integer(num)
      _ -> nil
    end
  end

  defp maybe_put(kw, _key, nil), do: kw
  defp maybe_put(kw, key, value), do: Keyword.put(kw, key, value)

  defp maybe_forward_opt(target, source_opts, key) do
    case Keyword.get(source_opts, key) do
      nil -> target
      [] -> target
      value -> Keyword.put(target, key, value)
    end
  end

  defp append_ref(acc, _type, nil), do: acc
  defp append_ref(acc, _type, ""), do: acc
  defp append_ref(acc, type, id), do: acc ++ [{type, id}]
end
